project/home/urls.py
""" All urls for the home application """
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('legal-notices/', views.LegalNoticeView.as_view(), name="legal_notices")
]

project/user/urls.py
""" All urls for the user application """
from django.urls import path
from django.contrib.auth.decorators import login_required
from  . import views


app_name = 'user'
urlpatterns = [
    path('register/', views.RegisterAccount.as_view(), name='register'),
    path('login/', views.LoginAccount.as_view(), name='login'),
    path('my/account/', login_required(views.MyAccount.as_view()), name='my_account'),
    path('my/substitutes/', login_required(views.MySubstitutes.as_view()), name='my_substitutes'),
    path(
        'delete_substitute/',
        login_required(views.MySubstitutes.as_view()),
        name='delete_substitutes'
    ),
    path('logout/', views.LogoutAccount.as_view(), name='logout'),
]

project/user/models.py
""" Inherit AbstractUser to add attributes """
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """ Create attributes email and subscribed """

    email = models.EmailField(unique=True, max_length=100)
    subscribed = models.BooleanField(default=False)

    def __str__(self):
        return self.email

project/user/forms.py
""" Inherit User Forms to add fields """
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User


class RegisterForm(UserCreationForm):
    """ Class to inherit userCreationForm and add a field """

    username = forms.CharField(
        max_length=40,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': _('Username'),
                'class': 'form-control'
            }
        ),
    )
    first_name = forms.CharField(
        max_length=40,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': _('First name'),
                'class': 'form-control'
            }
        ),
    )
    last_name = forms.CharField(
        max_length=40,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': _('Last name'),
                'class': 'form-control'
            }
        ),
    )
    email = forms.EmailField(
        max_length=250,
        required=True,
        widget=forms.EmailInput(
            attrs={
                'placeholder': _('Email'),
                'class': 'form-control'
            }
        ),
    )
    password1 = forms.CharField(
        max_length=128,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': _('Password'),
                'class': 'form-control'
            }
        ),
    )
    password2 = forms.CharField(
        max_length=128,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': _('Password confirmation'),
                'class': 'form-control'
            }
        ),
    )
    subscribed = forms.BooleanField(
        required=False,
        label=_('be informed of a V2 of the site ?'),
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'})
    )

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            'subscribed'
        ]


class LoginForm(AuthenticationForm):
    """ Class to inherit AuthenticationForm to display in wiew """

    username = forms.EmailField(
        max_length=250,
        required=True,
        widget=forms.EmailInput(
            attrs={
                'placeholder': _('Email'),
                'class': 'form-control'
            }
        ),
    )

    password = forms.CharField(
        max_length=128,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': _('Password'),
                'class': 'form-control'
            }
        ),
    )

project/user/views.py
""" All views for the user application """
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView, LogoutView
from django.http import JsonResponse
from product.models import Product
from .models import User
from .forms import RegisterForm, LoginForm


class RegisterAccount(View):
    """ Class View to display the the form register """

    template_name = 'user/register.html'
    form_class = RegisterForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password1 = form.cleaned_data['password1']
            subscribed = form.cleaned_data['subscribed']

            user = User.objects.filter(email=email)
            if not user.exists():
                user = User.objects.create_user(
                    username=username,
                    first_name=first_name,
                    last_name=last_name,
                    email=email,
                    password=password1,
                    subscribed=subscribed)
            else:
                user = user.first()
            login(request, user)
            return redirect('user:my_account')

        return render(request, self.template_name, {'form': form})


class LoginAccount(LoginView):
    """ Class View to display the the form login """

    template_name = 'user/login.html'
    authentication_form = LoginForm


class MyAccount(View):
    """ Class View to display the my account page """

    template_name = 'user/my_account.html'

    def get(self, request):
        return render(request, self.template_name)


class MySubstitutes(View):
    """ Class View to display the my substitutes page """

    template_name = 'user/my_substitutes.html'

    def get(self, request):
        if request.user.is_authenticated:
            products = User.objects.get(id=request.user.id).product_set.all()
            len_products = len(products)
            context = {'products': products, 'len': len_products}
        return render(request, self.template_name, context)

    def post(self, request):
        if request.user.is_authenticated:
            query = request.POST.get('product_id')
            product = Product.objects.get(id=query)
            user = User.objects.get(id=request.user.id)
            product.delete_substitute(user)

            res = {'good_message': 'delete'}
        else:
            res = {'error_message': 'impossible'}

        return JsonResponse(res)


class LogoutAccount(LogoutView):
    """ Class View to deconnect user """

    def get(self, request):
        logout(request)

        return redirect('home:home')

project/user/templates/user/login.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% translate 'Sign in' %}{% endblock %}
{% block css %}<link href="{% static 'css/account.css' %}" rel="stylesheet" />{% endblock %}
{% block content %}
<header class="masthead-account">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-12 col-lg-10 align-self-center">
                <h1 class="text-uppercase text-white font-weight-bold">{% translate 'Sign in' %}</h1>
                <hr class="divider my-4" />
            </div>
        </div>
    </div>
</header>
    <section class="">
        <div class="container mt-5">
            <div class="row align-items-center justify-content-center text-center">
                <div class="col-12 col-md-4">
                    {% include 'user/login_form.html' %}
                    <p>{% translate 'You do not have an account ? It is by' %} <a href="{% url 'user:register' %}">{% translate 'here' %}</a>.</p>
                </div>
            </div>
        </div>
    </section>
    
{% endblock %}

project/user/templates/user/login_form.html
{% load i18n %}
<form method="post" action="{% url 'user:login' %}" class="form_login">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
            {{ field }}
        </div>
    {% endfor %}
    {% if form.errors %}
        <div class="alert alert-danger">
            {% for key, value in form.errors.items %}
                <p>{{value}}</p>
            {% endfor %}
        </div>
    {% endif %}
    <button class="btn btn-primary mb-2" id="id_login" type="submit">{% translate 'Sign in' %}</button>
    {% if form.errors %}
        <div class="alert alert-danger">
            <p>{% translate 'Your username and password do not match.' %}</p>
        </div>
    {% endif %}
    <input type="hidden" name="next" value="{{ redirect_field_name }}" />
</form>

project/user/templates/user/my_account.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% translate 'My account' %}{% endblock %}
{% block css %}<link href="{% static 'css/account.css' %}" rel="stylesheet" />{% endblock %}

{% block content %}
<header class="masthead-account">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-12 col-lg-10 align-self-center">
                {% if user%}
                    <h1 class="text-uppercase text-white font-weight-bold">{{ user.first_name }}  {{ user.last_name }}</h1>
                    <hr class="divider my-4" />
                {% endif %}
            </div>
        </div>
    </div>
</header>
<section>
    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-12">
                {% if user %}
                    <h2 class="text-center">{{ user.email }}</h2>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="text-center">
                    <a href="{% url 'user:my_substitutes' %}" class="btn btn-primary text-white" id="view_products_user">{% translate 'See your products' %}</a>
                </div>
                <div class="list-products"></div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

project/user/templates/user/my_substitutes.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}Mon compte{% endblock %}
{% block css %}<link href="{% static 'css/account.css' %}" rel="stylesheet" />{% endblock %}

{% block content %}
<header class="masthead-account">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-12 col-lg-10 align-self-center">
                {% if user%}
                    <h1 class="text-uppercase text-white font-weight-bold">{{ user.first_name }}  {{ user.last_name }}</h1>
                    <hr class="divider my-4" />
                {% endif %}
            </div>
        </div>
    </div>
</header>
<section class="my_substitutes mt-5">
    <div class="container">
        {% if products %}
            <h2 class="text-center mb-5 mt-5">{% translate 'You have ' %}<span class="count_product">{{ len }}</span> {% translate 'substitute' %}{% if len > 1 %}s {% endif %} {% translate 'saved' %}{% if len > 1 %}s {% endif %}</h2>
            <div class="row">
                {% for product in products %}
                    <div class="col-12 col-md-4 mb-5 text-center" id="{{ product.id }}">
                        <div class="card" style="width: 18rem;">
                            <img class="img img-fluid card-img-top" src="{{ product.image }}" alt="{{ product.name }}">
                            <div class="card-body">
                                <a href="/product-{{ product.id }}">
                                    <p class="card-text">{{ product.name }}</p>
                                </a>
                                <form method="post" class="form-substitute-delete">
                                    {% csrf_token %}
                                    <input type="hidden" name="product" value="{{ product.id }}">
                                    <button type="submit" class="btn btn-primary delete_substitute"><i class="fas fa-trash"></i>{% translate ' Delete' %}</button>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <h2 class="text-center mb-5 mt-5">{% translate 'Your substitutes saved' %}</h2>
            <div class="row">
                <div class="col-12">
                    <p class="text-center">{% translate 'No registered substitutes.' %}</p>
                    <p class="text-center">{% translate 'Search for products: ' %}</p>
                    {% include 'home/search_form.html' %}
                </div>
            </div>
        {% endif %}
    </div>
</section>
{% endblock %}

{% block js %}<script src="{% static 'js/delete_substitute.js' %}"></script>{% endblock %}

project/user/templates/user/password_reset.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% translate 'Forgot your password?' %}{% endblock %}
{% block css %}<link href="{% static 'css/account.css' %}" rel="stylesheet" />{% endblock %}
{% block content %}
<header class="masthead-account">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-12 col-lg-10 align-self-center">
                <h1 class="text-uppercase text-white font-weight-bold">{% translate 'Forgot your password?' %}</h1>
                <hr class="divider my-4" />
            </div>
        </div>
    </div>
</header>
<section class="">
    <div class="container mt-5">
        <div class="row align-items-center justify-content-center text-center">
            <div class="col-12 col-md-4">
                <p>{% translate "Enter your email address below, and we'll email instructions for setting a new one." %}</p>
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {{ form }}
                    </fieldset>
                    <div class="form-group">
                        <button id="password_reset_btn" class="btn btn-primary mb-2" type="submit">{% translate 'Password reset' %}</button>
                    </div>
             </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

project/user/templates/user/password_reset_complete.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% translate 'Password validate' %}{% endblock %}
{% block css %}<link href="{% static 'css/account.css' %}" rel="stylesheet" />{% endblock %}
{% block content %}
<header class="masthead-account">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-12 col-lg-10 align-self-center">
                <h1 class="text-uppercase text-white font-weight-bold">{% translate 'Password validate' %}</h1>
                <hr class="divider my-4" />
            </div>
        </div>
    </div>
</header>
<section class="">
    <div class="container mt-5">
        <div class="row align-items-center justify-content-center text-center">
            <div class="col-12 col-md-4">
                <div class="alert alert-info">
                    {% translate 'Your password has been set.' %}
                </div>
                <a href="{% url 'user:login' %}">{% translate 'Sign In Here' %}</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

project/user/templates/user/password_reset_confirm.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% translate 'New password' %}{% endblock %}
{% block css %}<link href="{% static 'css/account.css' %}" rel="stylesheet" />{% endblock %}
{% block content %}
<header class="masthead-account">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-12 col-lg-10 align-self-center">
                <h1 class="text-uppercase text-white font-weight-bold">{% translate 'New password' %}</h1>
                <hr class="divider my-4" />
            </div>
        </div>
    </div>
</header>
<section class="">
    <div class="container mt-5">
        <div class="row align-items-center justify-content-center text-center">
            <div class="col-12 col-md-4">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {{ form }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-primary mb-2" type="submit">{% translate 'Reset Password' %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

project/user/templates/user/password_reset_done.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% translate 'Sent Email' %}{% endblock %}
{% block css %}<link href="{% static 'css/account.css' %}" rel="stylesheet" />{% endblock %}
{% block content %}
<header class="masthead-account">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-12 col-lg-10 align-self-center">
                <h1 class="text-uppercase text-white font-weight-bold">{% translate 'Sent email' %}</h1>
                <hr class="divider my-4" />
            </div>
        </div>
    </div>
</header>
<section class="">
    <div class="container mt-5">
        <div class="row align-items-center justify-content-center text-center">
            <div class="col-12 col-md-4">
                <p>{% translate "An email has been sent with instructions to reset your password." %}</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

project/user/templates/user/register.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% translate 'I create my account' %}{% endblock %}
{% block css %}<link href="{% static 'css/account.css' %}" rel="stylesheet" />{% endblock %}

{% block content %}
<header class="masthead-account">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-12 col-lg-10 align-self-center">
                <h1 class="text-uppercase text-white font-weight-bold">{% translate 'I create my account' %}</h1>
                <hr class="divider my-4" />
            </div>
        </div>
    </div>
</header>
<div class="container mt-5">
    <div class="row align-items-center justify-content-center text-center">
        <div class="col-12 col-md-4">
            <form action="" method="post" class="">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.field.widget.input_type == 'checkbox' %}
                        <div>
                            {{ field }}{{ field.label_tag }}
                        </div>
                    {% else %}
                        <div class="form-group">
                            {{ field }}
                        </div>
                    {% endif %}
                {% endfor %}
                {% if form.errors %}
                    <div class="alert alert-danger">
                        {% for key, value in form.errors.items %}
                            <p>{{value}}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <button class="btn btn-primary mb-2" id="id_signup" type="submit">{% translate 'Sign up' %}</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/cookies.js' %}"></script>
    <script src="{% static 'js/delete_substitute.js' %}"></script>
{% endblock %}