project/home/urls.py
""" All urls for the home application """
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('legal-notices/', views.LegalNoticeView.as_view(), name="legal_notices")
]

project/product/urls.py
""" All urls for the product application """
from django.urls import path
from  . import views

app_name = 'product'
urlpatterns = [
    path('search/', views.SearchProduct.as_view(), name='search'),
    path('search/substitutes/<int:product_id>/', views.Substitutes.as_view(), name='substitutes'),
    path('save_substitute/', views.Substitutes.as_view(), name='save_substitute'),
    path('product-<int:product_id>/', views.ProductView.as_view(), name='product'),
    path('change_number_list/', views.Substitutes.as_view(), name='change_number_list')
]

project/home/views.py
""" All views for the home application """
from django.shortcuts import render
from django.views import View


class IndexView(View):
    """ Homepage views """

    template_name = 'home/index.html'

    def get(self, request):
        return render(request, self.template_name)


class LegalNoticeView(View):
    """ Legal Notice view """

    template_name = 'home/legal_notice.html'

    def get(self, request):
        return render(request, self.template_name)

project/home/templates/home/index.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}

<!-- Masthead-->
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">{% translate 'Fat, yes, but of quality!' %}</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
                <h2 class="text-white-75 font-weight-light mb-5">{% translate 'Find a substitute for the ones you eat every day.' %}</h2>
            </div>
            <div class="col-12 col-md-8 align-self-baseline">
                {% include 'home/search_form.html' %}
            </div>
        </div>
    </div>
</header>
<!-- About-->
<section class="page-section bg-primary" id="about">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="text-white mt-0">{% translate 'Colette and Rémy' %}</h2>
                <hr class="divider light my-4" />
                <p class="text-white-50 mb-4">{% translate 'Pur Beurre is the initiative of two lovers of French gastronomy, Colette Tatou and Rémy, whom you have certainly already met in our excellent restaurant Ratatouille.' %}</p>
                <ul class="identity-pb">
                    <li class="mb-2"><span>Colette Tatou : </span>"{% translate 'We all love to eat, especially in France! Personally, a fresh baguette, good goat cheese and a good red wine are enough for me. Like everyone else, I do my shopping at the supermarket. But gradually I realized, especially when we opened the restaurant, that I could replace the sanitized products that I used to buy with good local products And often for the same price!' %}"</li>
                    <li><span>Remy : </span>"{% translate 'For my part, I was already going to many stores because I really like to walk around, especially in cellars and kitchens. I knew by heart the contents of the organic shops (which I love) as well as the ingredients of all the foods sold. When Colette asked me if she could replace her morning Nutella with something healthier, I knew immediately where to find it. The idea of Pur Beurre was born!' %}"</li>
                </ul>
            </div>
        </div>
        <div class="row justify-content-center">
            <div>
                <figure>
                    <img class="img img-fluid" src="{% static 'img/colette.png' %}" alt="Colette">
                    <figcaption>
                        <p class="text-center">Colette</p>
                    </figcaption>
                </figure>
            </div>
            <div>
                <figure>
                    <img class="img img-fluid" src="{% static 'img/remy.png' %}" alt="Remy">
                    <figcaption>
                        <p class="text-center">Remy</p>
                    </figcaption>
                </figure>
            </div>
        </div>
    </div>
</section>
<!-- Contact-->
<section class="page-section bg-dark text-white" id="contact">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="mt-0">{% translate 'Contact us !' %}</h2>
                <hr class="divider my-4" />
                <p class="text-white mb-5">{% translate 'Ready to take care of yourself?' %}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                <div>+1 (555) 123-4567</div>
            </div>
            <div class="col-lg-4 mr-auto text-center">
                <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                <!-- Make sure to change the email address in BOTH the anchor text and the link target below!-->
                <a class="d-block" href="mailto:contact@purbeurre.com">contact@purbeurre.com</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

project/home/templates/home/legal_notice.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% translate 'Legal notices' %}{% endblock %}
{% block content %}
<!-- Masthead-->
<header class="masthead-legal-notice">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-12 col-lg-10 align-self-center">
                <h1 class="text-uppercase text-white font-weight-bold">{% translate 'Legal notices' %}</h1>
                <hr class="divider my-4" />
            </div>
        </div>
    </div>
</header>
<div class="container mt-5" id="page_legal">
    <section>
        <h2>{% translate 'Legal informations' %}</h2>
        <p>{% translate 'By virtue of article 6 of law n ° 2004-575 of June 21, 2004 on confidence in the digital economy, it is clear to users of the purbeurre.fr site, the identity of the various shareholders within the framework of its realization and its follow-up:' %}</p>
        <p>{% translate 'In accordance with the "Informatique et Libertés" law of January 6, 1978, this site is the subject of a declaration to the CNIL - dated November 19, 2015 - receipt of declaration n ° 190 6255' %}</p>
    </section>
    <section>
        <h2>{% translate 'Owner' %}</h2>
        <p>{% translate 'Colette and Rémy' %}</p>
    </section>
    <section>
        <h2>{% translate 'Brand' %}</h2>
        <p>"Pur Beurre"</p>
    </section>
    <section>
        <h2>{% translate 'Catch phrase' %}</h2>
        <p>"{% translate 'Fat, yes, but of quality!' %}"</p>
    </section>
    <section>
        <h2>Designer / Webhost</h2>
        <p>Pur Beurre</p>
    </section>
</div>
{% endblock %}

project/home/templates/home/search_form.html
{% load i18n %}
<form method="get" action="{% url 'product:search' %}" class="form-search form-inline justify-content-center">
    {% csrf_token %}
    <div role="search" class="">
        <input type="text" name="search" class="form-control mb-2 mr-sm-2 search-query" placeholder="{% translate 'Product' %}" required data-limit="5"/>
    </div>
    <button  class="btn btn-primary mb-2" type="submit">{% translate 'Search' %}</button>
</form>